name: workflow events used in GitHub Actions

on:
  schedule:
    - cron: "*/1 * * * *" # Every minute

jobs:
  testjob:
    runs-on: ubuntu-latest
    steps:
      - name: Hello Greet
        run: echo "Hello from schedule_event"
