name: workflow events used in giyhub actions

# on: workflow_dispatch
on:
  schedule:
    - cron: "*/1 * * * *"

jobs:
  testjob:
    runs-on: ubuntu-latest
    steps:
      - name: hellogreet
        run: echo "hello workflowdispatch_event"
